### ISSUE TITLE
Scripts break when reaching yE

### ISSUE THREAD

**Issue by phk01** [krypted/brutalkeychain#1]
As you can see from attatchet image the script breaks when reaching aaaaaaaaaayE, it's done this on every test I have ran.

I've tested char lengths of 8, 11 & 12 and it erros out at the same spot.

If you need me to do any further testing please let me know.

Command issued: ./BruteforceKeychain\ 2 -l 8 -n login.keychain-db

<img width="1139" alt="Screenshot 2022-01-03 at 15 04 42" src="https://user-images.githubusercontent.com/46556885/147939801-e6cdb3ff-9d75-4c55-8e33-edef5d7ead31.png">

**Comment by krypted** [comment]
Ohhhh, I forgot to close my pipes:

try! outpipe.fileHandleForReading.close() 
try! errpipe.fileHandleForReading.close()

Will fix when I get a chance. Thanks for pointing that out.
